"""change the table name and delete one tow

Revision ID: 4affa5e2151f
Revises: 6a1c28bba947
Create Date: 2025-03-03 17:53:39.896925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4affa5e2151f'
down_revision: Union[str, None] = '6a1c28bba947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_table_id'), 'todos_table', ['id'], unique=False)
    op.create_index(op.f('ix_todos_table_title'), 'todos_table', ['title'], unique=False)
    op.drop_index('ix_todos_id', table_name='todos')
    op.drop_index('ix_todos_title', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.create_index('ix_todos_title', 'todos', ['title'], unique=False)
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    op.drop_index(op.f('ix_todos_table_title'), table_name='todos_table')
    op.drop_index(op.f('ix_todos_table_id'), table_name='todos_table')
    op.drop_table('todos_table')
    # ### end Alembic commands ###
