"""create todos table

Revision ID: 6a1c28bba947
Revises: 
Create Date: 2025-03-03 17:33:04.239364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a1c28bba947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new table to practice in table plus')
    op.drop_table('first_table')
    op.add_column('todos', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('todos', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('todos_title_key', 'todos', type_='unique')
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.drop_column('todos', 'status1')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('status1', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.create_unique_constraint('todos_title_key', 'todos', ['title'])
    op.alter_column('todos', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('todos', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('todos', 'status')
    op.create_table('first_table',
    sa.Column('column_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('my_record', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('new table to practice in table plus',
    sa.Column('name', sa.VARCHAR(), server_default=sa.text("'address'::character varying"), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
