"""add new column completed in todo table

Revision ID: d2626a676d7a
Revises: 4affa5e2151f
Create Date: 2025-03-03 19:04:51.108216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2626a676d7a'
down_revision: Union[str, None] = '4affa5e2151f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos_table', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos_table', 'completed')
    # ### end Alembic commands ###
